version: 0.2
env:
  # parameter-store:
  #   NPMRC_TOKEN: /codeBuild/npmrc_token
  # variables:
  #   NPMRC_TOKEN: npmrc_token
phases: 
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Executing install phase
    finally:
      - echo Executing install phase COMPLETE
      - echo $NPMRC_TOKEN
      - echo //npm.pkg.github.com/:_authToken=$NPMRC_TOKEN > ~/.npmrc
  pre_build:
    commands:
      - cd client
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cd ..
      - mkdir temp
      - mkdir temp/build
      - mkdir temp/build/rowilab
      - mkdir temp/build/rowilabViewer
      - cp -R ./client/build/* temp/build/rowilab
      - cp -R ./server temp/build/rowilab/server
      - cp -R ./viewer/* temp/build/rowilabViewer
      - cp -R ./appspec.yml temp/appspec.yml
      - cp -R ./awsCICD temp/awsCICD

artifacts:
  files:
    - "**/*"
  base-directory: "temp"

#   discard-paths: yes

  # post_build:
    # commands:
      # - aws s3 cp --recursive ./build s3://rowilab.ae/